#!/usr/bin/env bash
# Prepare everything the runner needs, but do NOT activate it yet.
#
#   - verifies the runner binary exists
#   - verifies the sudoers NOPASSWD rule works
#   - creates ~/.clamshell-taskq/ with a .env placeholder and the run.sh wrapper
#   - writes the LaunchAgent plist (with RunAtLoad=true)
#
# After this finishes, edit ~/.clamshell-taskq/.env, then run
# scripts/setup-launchd-start.sh to activate the schedule.

set -euo pipefail

if [[ "$(uname)" != "Darwin" ]]; then
    echo "error: macOS only" >&2
    exit 1
fi

USER_NAME=$(whoami)
HOME_DIR=$HOME
RUNNER_BIN=/usr/local/bin/clamshell-runner
ENV_DIR="$HOME_DIR/.clamshell-taskq"
ENV_FILE="$ENV_DIR/.env"
RUN_SCRIPT="$ENV_DIR/run.sh"
PLIST_PATH="$HOME_DIR/Library/LaunchAgents/com.clamshell-taskq.runner.plist"
LOG_OUT="$ENV_DIR/launchd.out.log"
LOG_ERR="$ENV_DIR/launchd.err.log"

# ---------- preflight ----------

if [[ ! -x "$RUNNER_BIN" ]]; then
    cat <<EOF >&2
error: $RUNNER_BIN not found or not executable.

Build and install the binary first:
    go build -o bin/runner ./cmd/runner
    sudo install -m 0755 bin/runner $RUNNER_BIN
EOF
    exit 1
fi

# Verify NOPASSWD rule by asking sudo whether the command would be
# allowed without a password (-l -n lists the permission, does NOT
# execute the command — so nothing gets scheduled).
if ! sudo -l -n /usr/bin/pmset schedule wake "$(date '+%m/%d/%Y %H:%M:%S')" >/dev/null 2>&1; then
    cat <<EOF >&2
error: 'sudo pmset schedule wake' is not configured for passwordless use.

Run the sudoers installer first:
    ./scripts/setup-sudoers.sh
EOF
    exit 1
fi

echo "==> Preparing runner files for user: $USER_NAME"

# ---------- env directory ----------

mkdir -p "$ENV_DIR"
chmod 700 "$ENV_DIR"
echo "    ensured  $ENV_DIR"

# ---------- run.sh wrapper ----------

cat > "$RUN_SCRIPT" <<EOF
#!/bin/bash
# Auto-generated by setup-launchd-ready.sh. Do not edit by hand.
set -a
source "$ENV_FILE"
set +a
"$RUNNER_BIN"
/usr/bin/sudo /usr/bin/pmset schedule wake "\$(date -v+5M -v0S -v-10S '+%m/%d/%Y %H:%M:%S')"
EOF
chmod 700 "$RUN_SCRIPT"
echo "    wrote    $RUN_SCRIPT"

# ---------- LaunchAgent plist (NOT loaded yet) ----------

mkdir -p "$HOME_DIR/Library/LaunchAgents"
{
    cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.clamshell-taskq.runner</string>

  <key>ProgramArguments</key>
  <array>
    <string>$RUN_SCRIPT</string>
  </array>

  <key>RunAtLoad</key>
  <true/>

  <key>StartCalendarInterval</key>
  <array>
EOF
    for m in 0 5 10 15 20 25 30 35 40 45 50 55; do
        printf '    <dict><key>Minute</key><integer>%d</integer></dict>\n' "$m"
    done
    cat <<EOF
  </array>

  <key>WorkingDirectory</key>
  <string>$ENV_DIR</string>
  <key>StandardOutPath</key>
  <string>$LOG_OUT</string>
  <key>StandardErrorPath</key>
  <string>$LOG_ERR</string>
</dict>
</plist>
EOF
} > "$PLIST_PATH"
echo "    wrote    $PLIST_PATH  (NOT loaded yet)"

cat <<EOF

==> Done. Files are ready but the schedule is NOT active yet.

Next steps
  1. Copy your .env into place:
       cp .env $ENV_FILE
       chmod 600 $ENV_FILE
     The file must define SLACK_BOT_TOKEN, SLACK_TASK_CHANNEL, COMMAND.
  2. Activate the schedule:
       ./scripts/setup-launchd-start.sh
EOF
