#!/usr/bin/env bash
# Prepare everything the runner needs, but do NOT activate it yet.
#
#   - verifies the runner binary exists
#   - verifies the sudoers NOPASSWD rule works
#   - creates ~/.clamshell-taskq/ with a .env placeholder and the run.sh wrapper
#   - writes the LaunchAgent plist (with RunAtLoad=true)
#
# After this finishes, edit ~/.clamshell-taskq/.env, then run
# scripts/setup-launchd-start.sh to activate the schedule.

set -euo pipefail

if [[ "$(uname)" != "Darwin" ]]; then
    echo "error: macOS only" >&2
    exit 1
fi

USER_NAME=$(whoami)
HOME_DIR=$HOME
RUNNER_BIN=/usr/local/bin/clamshell-runner
ENV_DIR="$HOME_DIR/.clamshell-taskq"
ENV_FILE="$ENV_DIR/.env"
RUN_SCRIPT="$ENV_DIR/run.sh"
PLIST_PATH="$HOME_DIR/Library/LaunchAgents/com.clamshell-taskq.runner.plist"
LOG_OUT="$ENV_DIR/launchd.out.log"
LOG_ERR="$ENV_DIR/launchd.err.log"

# ---------- preflight ----------

if [[ ! -x "$RUNNER_BIN" ]]; then
    cat <<EOF >&2
error: $RUNNER_BIN not found or not executable.

Build and install the binary first:
    go build -o bin/runner ./cmd/runner
    sudo install -m 0755 bin/runner $RUNNER_BIN
EOF
    exit 1
fi

# Verify the NOPASSWD rules by asking sudo whether each command would be
# allowed without a password (-l -n lists the permission, does NOT execute
# the command — so nothing gets scheduled and no flag gets flipped).
if ! sudo -l -n /usr/bin/pmset schedule wake "$(date '+%m/%d/%Y %H:%M:%S')" >/dev/null 2>&1; then
    cat <<EOF >&2
error: 'sudo pmset schedule wake' is not configured for passwordless use.

Run the sudoers installer first:
    ./scripts/setup-sudoers.sh
EOF
    exit 1
fi

if ! sudo -l -n /usr/bin/pmset -a disablesleep 1 >/dev/null 2>&1; then
    cat <<EOF >&2
error: 'sudo pmset -a disablesleep' is not configured for passwordless use.

This is what keeps the machine awake while a task runs. Re-run the sudoers
installer to add the rule:
    ./scripts/setup-sudoers.sh
EOF
    exit 1
fi

echo "==> Preparing runner files for user: $USER_NAME"

# ---------- env directory ----------

mkdir -p "$ENV_DIR"
chmod 700 "$ENV_DIR"
echo "    ensured  $ENV_DIR"

# ---------- run.sh wrapper ----------

cat > "$RUN_SCRIPT" <<EOF
#!/bin/bash
# Auto-generated by setup-launchd-ready.sh. Do not edit by hand.

# Hold an idle-sleep assertion for the whole cycle (Slack check + wake
# re-arm) by re-exec'ing under caffeinate once. Without it, a short or
# unstable dark wake can sleep mid-cycle and the next wake never gets armed.
if [[ -z "\${CLAMSHELL_CAFFEINATED:-}" ]]; then
    export CLAMSHELL_CAFFEINATED=1
    exec /usr/bin/caffeinate -i "\$0" "\$@"
fi

set -a
source "$ENV_FILE"
set +a
# SleepDisabled is the only thing that survives a lid close; caffeinate and
# other power assertions do not. Set it before the runner, which needs the
# network that a short dark wake denies.
/usr/bin/sudo /usr/bin/pmset -a disablesleep 1

"$RUNNER_BIN"

# Release unless a task is running. Snapshot ps first -- piping into grep
# always hits, because grep's own argv carries \$COMMAND.
procs=\$(ps -Ao args=)
case "\$procs" in
    *"\$COMMAND"*) : ;;
    *)             /usr/bin/sudo /usr/bin/pmset -a disablesleep 0 ;;
esac

# Re-arm the next cycle by bracketing the boundary with several wakes
# (-10/-5/0/+5/+10s). A short battery dark wake often fails to run launchd at a
# single instant, so give it multiple shots around the boundary -- including
# +5/+10s, where the job is already overdue and launchd runs it on the wake
# itself (the more reliable path).
for off in -10 -5 0 +5 +10; do
    /usr/bin/sudo /usr/bin/pmset schedule wake "\$(date -v+5M -v0S -v\${off}S '+%m/%d/%Y %H:%M:%S')"
done
EOF
chmod 700 "$RUN_SCRIPT"
echo "    wrote    $RUN_SCRIPT"

# ---------- LaunchAgent plist (NOT loaded yet) ----------

mkdir -p "$HOME_DIR/Library/LaunchAgents"
{
    cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.clamshell-taskq.runner</string>

  <key>ProgramArguments</key>
  <array>
    <string>$RUN_SCRIPT</string>
  </array>

  <key>RunAtLoad</key>
  <true/>

  <key>StartCalendarInterval</key>
  <array>
EOF
    for m in 0 5 10 15 20 25 30 35 40 45 50 55; do
        printf '    <dict><key>Minute</key><integer>%d</integer></dict>\n' "$m"
    done
    cat <<EOF
  </array>

  <key>WorkingDirectory</key>
  <string>$ENV_DIR</string>
  <key>StandardOutPath</key>
  <string>$LOG_OUT</string>
  <key>StandardErrorPath</key>
  <string>$LOG_ERR</string>
</dict>
</plist>
EOF
} > "$PLIST_PATH"
echo "    wrote    $PLIST_PATH  (NOT loaded yet)"

cat <<EOF

==> Done. Files are ready but the schedule is NOT active yet.

Next steps
  1. Copy your .env into place:
       cp .env $ENV_FILE
       chmod 600 $ENV_FILE
     The file must define SLACK_BOT_TOKEN, SLACK_TASK_CHANNEL, COMMAND.
  2. Activate the schedule:
       ./scripts/setup-launchd-start.sh
EOF
